name: update release
on:
  workflow_dispatch:
jobs:
  update-release:
    runs-on: ubuntu-latest
    #    permissions:
    #      contents: write # 書き込むために必要
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go 1.21.3
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.3'
      - name: info
        run: |
          echo pwd; pwd
          echo ls; ls -al
          echo find; find $(pwd) -type f
      - name: test
        run: |
          go test ./...
      - name: install require package
        run: |
          sudo apt-get install -y \
            pv \
            g++-aarch64-linux-gnu
      - name: push to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash ./scripts/build.sh





#
#name: build
#
#on:
#  pull_request:
#
#  push:
#    branches:
#      - main
#    tags:
#      - v*
#
#  workflow_dispatch:
#
#  schedule:
#    - cron: '0 0 * * 1'

#jobs:
#  build:
#    strategy:
#      matrix:
#        go: [ '1.16', '1.x' ]
#        os: [ ubuntu-latest, macos-latest ]
#
#    runs-on: ${{ matrix.os }}
#
#    name: ${{ matrix.os }}/${{ matrix.go }}
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Install Go
#        uses: actions/setup-go@v5
#        with:
#          go-version: ${{ matrix.go }}
#
#      - name: Build
#        run: go build
#
#      - name: Check
#        run: ./httpshd -help
